# Generated by Django 3.2.9 on 2021-12-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuelements',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='menuelements',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
